name: Test Badge

permissions:
  contents: write

on:
  push:
    branches:
      - dev
      - master
      - feature/badge

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [utils]
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Run dotnet ci action
        uses: eanzhao/frontend-ci@v0.0.5
        with:
          commit-token: ${{ secrets.COMMIT_TOKEN }}
          branch-name: "feature/badge-json"
          is-monorepo: true
          package: ${{ matrix.package }}